// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcLwZZOKK352DMS0-Q5gO-dNQgfm39v0o',
    appId: '1:213196652022:android:e79869c736ce054040dbd7',
    messagingSenderId: '213196652022',
    projectId: 'doctor-t-7a5b5',
    databaseURL: 'https://doctor-t-7a5b5-default-rtdb.firebaseio.com',
    storageBucket: 'doctor-t-7a5b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZC8lAeqFOCx_VwGutxTuefe6YaG1Ac1w',
    appId: '1:213196652022:ios:eb2dd4f1ef563f8740dbd7',
    messagingSenderId: '213196652022',
    projectId: 'doctor-t-7a5b5',
    databaseURL: 'https://doctor-t-7a5b5-default-rtdb.firebaseio.com',
    storageBucket: 'doctor-t-7a5b5.appspot.com',
    iosClientId: '213196652022-l56vhpkkq23b6sb3gfj87ep7g7dedsr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
